[package]
name = "highlight"
edition.workspace = true

[dependencies]
html = { path = "../html" }
tree-sitter-highlight = "0.25.10"

[dev-dependencies]
tree-sitter-languages = { path = "../tree-sitter-languages", features = ["rust"] }
