[package]
name = "znak"
edition.workspace = true

[lints]
workspace = true

[dependencies]
highlight = { path = "../highlight" }
html = { path = "../html" }
math = { path = "../math" }

[dev-dependencies]
highlight = { path = "../highlight", features = ["python"] }
