[package]
name = "znak"
edition.workspace = true

[dependencies]
highlight = { path = "../highlight" }
html = { path = "../html" }
math = { path = "../math" }

[dev-dependencies]
tree-sitter-languages = { path = "../tree-sitter-languages", features = ["python"] }
